apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  # namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: quay.io/skupper/hello-world-frontend
        # securityContext:
        #   runAsUser: 0
        #   allowPrivilegeEscalation: true
        # resources:
        #   requests:
        #     memory: "1Mi"     # Very low memory request (8 megabytes)
        #     cpu: "1m"        # Very low CPU request (0.01 cores)
        #   limits:
        #     memory: "1Mi"    # Very low memory limit (16 megabytes)
        #     cpu: "1m"        # Low CPU limit (0.05 cores)
